package com.bgsoftware.wildstacker.api.objects;

import org.bukkit.block.CreatureSpawner;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.LivingEntity;
import org.bukkit.inventory.ItemStack;

import java.util.List;

public interface StackedSpawner extends StackedObject<CreatureSpawner>, UpgradeableStackedObject {

    /**
     * Get the creature-spawner object of bukkit.
     */
    CreatureSpawner getSpawner();

    /**
     * Get the spawned-type of the creature-spawner.
     */
    EntityType getSpawnedType();

    /**
     * Get the entity that is linked into this spawner.
     * May be null if there is no linked entity or it's too far away.
     */
    LivingEntity getLinkedEntity();

    /**
     * Set an entity to be linked into this spawner.
     *
     * @param linkedEntity an entity to link
     */
    void setLinkedEntity(LivingEntity linkedEntity);

    /**
     * Get all the nearby stacked-spawners that the spawner can stack into in the merge range.
     */
    List<StackedSpawner> getNearbySpawners();

    /**
     * Get the drop item of the spawner.
     */
    ItemStack getDropItem();

    /**
     * Get the drop item of the spawner.
     *
     * @param amount the amount of the item to drop.
     */
    ItemStack getDropItem(int amount);

    /**
     * Check if the spawner is natural.
     * A natural spawner is a spawner that was generated by the world and not placed by a player.
     *
     * @return true if the spawner is natural, false otherwise.
     */
    boolean isNatural();

    /**
     * Set the natural state of the spawner.
     * This is used to mark a spawner as natural or not.
     *
     * @param natural true if the spawner is natural, false otherwise.
     */
    void setNatural(boolean natural);


}
