package com.bgsoftware.wildstacker.api.enums;

public enum StackCheckResult {

    NOT_ENABLED,
    NOT_SIMILAR,
    NOT_WHITELISTED,
    BLACKLISTED,
    DISABLED_WORLD,
    BLACKLISTED_NAME,
    ALREADY_DEAD,
    TARGET_NOT_WHITELISTED,
    TARGET_BLACKLISTED,
    TARGET_DISABLED_WORLD,
    TARGET_BLACKLISTD_NAME,
    TARGET_ALREADY_DEAD,
    CORPSE,
    LIMIT_EXCEEDED,
    DISABLED_REGION,
    NOT_BELOW,
    INSIDE_PORTAL,
    TARGET_INSIDE_PORTAL,
    SUCCESS

}
